### PR TITLE
feat: Add Portuguese translation

### PR DESCRIPTION
**Pull request by venelouis**
## Description
Add Portuguese translation: https://github.com/venelouis/intro/tree/pt-translations
Here you can see the changes: https://github.com/open-sauced/intro/pull/235/files

## Related Tickets & Documents
Docs #234

## Mobile & Desktop Screenshots/Recordings
image

## Steps to QA
1. See the modifications: https://github.com/open-sauced/intro/pull/235/files
2. Compare
3. Merge if you agree

Added to documentation?
[x ] 📜 README.md

Our discussion link for Portuguese repo: https://github.com/venelouis/intro/discussions/1
The changes I made: https://github.com/open-sauced/intro/pull/235/files

What type of PR is this? (check all applicable)
[x ] 🍕 Feature
[ x] 📝 Documentation Update

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [ ] Tier 4

## [optional] What gif best describes this PR or how it makes you feel? 
🇧🇷  🇵🇹  😃 
image

### CODE REVIEW

**Comment by venelouis** [comment]
I really don't know how to solve this, anyone can help me please?

**Comment by venelouis** [comment]
ok, now my pr it is green at least \o/ ✅

**Comment by CBID2** [comment]
Hi @venelouis. There are guidelines for translating the course into different languages. I highly recommend closing this Pull Request and [reading it](https://github.com/open-sauced/intro/blob/main/contributing/i18n-guidelines.md).

**Comment by venelouis** [comment]
@CBID2 yes I know, I read all. Is there anything wrong with my PR?

**Comment by CBID2** [comment]
> @CBID2 yes I know, I read all. Is there anything wrong with my PR?

Yes, to simplify why, check out this announcement:

**Comment by venelouis** [comment]
@CBID2 I see there a Spanish community translation right? Why isn't it there, how did I put mine? I don't understand, from what I understand I think I did everything right.

**Comment by CBID2** [comment]
> @CBID2 I see there a Spanish community translation right? Why isn't it there, how did I put mine? I don't understand, from what I understand I think I did everything right.

You going to have to deploy it separately. @adiati98, can you explain a bit more about the translation process?

**Comment by samucodesh** [comment]
> @CBID2 I see there a Spanish community translation right? Why isn't it there, how did I put mine? I don't understand, from what I understand I think I did everything right.

Hello @venelouis 

I strongly recommend using [this issue](https://github.com/open-sauced/intro/issues/212) as a reference point for the translation.

**Comment by venelouis** [comment]
Yes I know, but you profile and link shouldn't they be on the list?

**Comment by venelouis** [comment]
yes, i know, I just included my profile where I think it should be, did you see the

**Comment by samucodesh** [comment]
> Yes I know, @samucodesh but you profile and link shouldn't they be on the list?

Hello @venelouis 

My profile is currently unavailable due to ongoing project migration and translation. The repository has undergone multiple refactoring processes, and my current work is based on a previous version.

**Comment by venelouis** [comment]
Thank you @samucodesh and @CBID2. Sorry about any inconvenience.

**Pull request closed without merging**
