### PR TITLE
fix(favicon): moved the favicon to /static/img in order to show up in…

### LINKED ISSUE #236: Feature: Add favicon to Docusaurus app at opensauced.pizza/learn
## Current Behavior
The favicon icon is not showing up in the Docusaurus documentation app located at opensauced.pizza/learn.

## Proposed Solution
Implement a favicon for the Docusaurus app to improve visual identification in browser tabs and bookmarks.

## Additional Details
- Screenshots demonstrating the current issue.

Screenshot 2024-09-19 at 2 06 44 PM

Screenshot 2024-09-19 at 4 14 54 PM

## Benefits
Adding a favicon will:
1. Enhance brand recognition
2. Improve user experience by making the site easily identifiable in browser tabs and bookmarks
3. Align the documentation site with standard web practices

### PR DESCRIPTION
**Pull request by ivngzmn**
## Description

This PR adds a favicon to the Docusaurus documentation app located at opensauced.pizza/learn. The favicon was missing, which affected visual identification in browser tabs and bookmarks.

## Related Tickets & Documents
Fixes #236 

## Mobile & Desktop Screenshots/Recordings

Screenshot 2024-09-19 at 2 06 44 PM

Screenshot 2024-09-19 at 4 14 54 PM

## Steps to QA
1. Pull this branch and run the Docusaurus app locally
2. Open the app in a web browser
3. Verify that the favicon appears in the browser tab
4. Check different browsers (Chrome, Firefox, Safari, etc.) to ensure consistency

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [ ] Tier 4

## [optional] What gif best describes this PR or how it makes you feel?

tmnt

### CODE REVIEW

**Comment by adiati98** [comment]
Hey @ivngzmn,
First of all, we appreciate your contribution to improve our education website! ✨ 

However, please read our [contributing guidelines](https://github.com/open-sauced/intro/blob/main/contributing/CONTRIBUTING.md) carefully. That being said, can you please assign yourself to the issue before we can review your PR? 

Thanks! 🙂

**Comment by ivngzmn** [comment]
@adiati98 Will do.

**Review by adiati98 — COMMENTED** [review]
@ivngzmn I tested your changes locally. The favicon is there, but the logo on the navbar is broken as screenshot below.

Broken logo

Can you please share the screenshot of the page when you run your changes locally?

Another thing I'd like to ask, could you go to the `main` branch locally and run it? Can you see the favicon on the tab? 

Thank you.

**Comment by ivngzmn** [comment]
Hi @adiati98, 

Thank you for catching that! I have attached a screenshot of the page from when the changes ran locally.

Screenshot 2024-09-20 at 12 58 13 PM

Regarding the navigation logo, I went to the main branch locally and confirmed that the favicon was displaying. The issue was with the navbar logo path. I have updated the path accordingly and pushed the changes for review.

Thanks again for your help!

**Review by adiati98 — APPROVED** [review]
Thank you for the fix, @ivngzmn!🚢✨ 

---

@BekahHW below is the screenshot of the favicon and logo after the changes of the paths.

Screenshot 2024-09-20 223108

**Review by BekahHW — APPROVED** [review]

**Pull request merged**
