### PR TITLE
Fix: links, capitalization and wording adjustment in the "Tools to be Successful" chapter

### PR DESCRIPTION
**Pull request by Haimantika**
## Description
This PR fixes links, capitalization and wording adjustment in the "Tools to be Successful" chapter.

## What type of PR is this? (check all applicable)

- [x] 🐛 Bug Fix
- [x] 📝 Documentation Update

## Related Tickets & Documents
Fixes https://github.com/open-sauced/intro/issues/129

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by adiati98 — CHANGES_REQUESTED** [review]
Hi @Haimantika 

Thank you for working on this! ✨️
Before we review your PR, can you please:

- Change the title of your PR with this format: 
   ```markdown
   fix: things that changed 
   ```
- Fill in the description section with the details of your changes.

Completing PR form is necessary for maintainers to understand the changes that have been made in the PR.

And we have the guide about how to work with PR in our repos written in our [contributing guidelines](https://docs.opensauced.pizza/contributing/introduction-to-contributing/#pull-requests-pr). Please take a moment to read it. 😊

Please let me know when you're done. Thank you!

**Comment by Haimantika** [comment]
> Hi @Haimantika
> 
> Thank you for working on this! ✨️ Before we review your PR, can you please:
> 
> * Change the title of your PR with this format:
>   ```
>   fix: things that changed 
>   ```
> * Fill in the description section with the details of your changes.
> 
> Completing PR form is necessary for maintainers to understand the changes that have been made in the PR.
> 
> And we have the guide about how to work with PR in our repos written in our [contributing guidelines](https://docs.opensauced.pizza/contributing/introduction-to-contributing/#pull-requests-pr). Please take a moment to read it. 😊
> 
> Please let me know when you're done. Thank you!

Made the changes. Thanks for the comment. I missed these from the contributing guide.

**Comment by adiati98** [comment]
Also, I see that you made changes directly on your `main` branch.

We won't merge PRs that's been working on `main` branch to avoid unexpected production fails.

For that reason, I'm closing this PR. 🙏

Please create a new PR and make sure that you create a new branch before working on it.

Thank you! 😊

**Comment by adiati98** [comment]
Fixed in #133

**Pull request closed without merging**
