### PR TITLE
Created a consistency with guestbook term.

### LINKED ISSUE #105: Bug: Create consistency with guestbook term
### Describe the bug

Currently, we have guestbook and guest book mentioned in the course. For consistency, let's use the compound word, guestbook, throughout the repository.

### Steps to reproduce

1. Open the repo
2. Search for guest book
3. See 11 occurrences all in [https://github.com/open-sauced/intro/blob/main/05-how-to-contribute-to-open-source.md](https://github.com/open-sauced/intro/blob/main/05-how-to-contribute-to-open-source.md)

Let's replace all of those with guestbook.

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by rd-sharma7**
## Description
In a file , all (11) occurance of words [guest ,book] replaced with compounded word `"guestbook" ` .

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [X] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Closes #105

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?
It is my first PR ,I love it and mine dopamine is too high 😃

### CODE REVIEW

**Review by BekahHW — APPROVED** [review]

**Comment by BekahHW** [comment]
@rd-sharma7 thanks so much! Can you just make sure that your PR mentions the issue in the  description section likes this: `closes #106` so it will automatically close the issue when the PR is merged in?

**Comment by rd-sharma7** [comment]
Thanks for reviewed @BekahHW 
Sure, now it's get updated . 
I will ensure that from now.Hopes will got merged soon:)

**Comment by at-the-vr** [comment]
GitHub's pipeline won't detect the `Closes XXX` after PR is generated. One way maintainers can ensure it functions is [Linking the PR to issue manually](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-or-branch-to-an-issue-using-the-issue-sidebar)

**Comment by rd-sharma7** [comment]
Task done ! @at-the-vr

**Comment by rd-sharma7** [comment]
Task done ! @at-the-vr

**Review by CBID2 — APPROVED** [review]
Well done,@ 🙌

If you haven't, you can join our community Discord. 😊
Also, check out our pizza-verse repo if you want to contribute further! 🍕

**Comment by rd-sharma7** [comment]
Thankyou @CBID2  :)  .
Yes, I looks  further to contribute in given repo.

**Pull request merged**
