### PR TITLE
Fix #118 : Bug: Fix wording in the Intro section

### LINKED ISSUE #118: Bug: Fix wording in the "Intro" section
### Describe the bug

Currently, we have these in the "Intro" section:

- The intro sentence is: "Welcome to the "Getting Started with Open Source" course!"
   But our course's name is "Intro to Open Source with OpenSauced". 
- A section with the title "LFG".
   This title is non-inclusive, as non-native English speakers might not know what it stands for without googling.

So, we need to change these.

### Suggested Solutions

- [ ] Change the intro sentence.
  
   ```diff
   - Welcome to the "Getting Started with Open Source" course!
   + Welcome to the "Intro to Open Source with OpenSauced" course!
   ```

   **Code snippet:**
   https://github.com/open-sauced/intro/blob/59b55ca73787bbadda275d8b4caabd5e7be0595b/01-intro.md?plain=1#L3

- [ ] Change the title "LFG 🚀 " to "Let's Get Started 🚀 "

   ```diff
   - ## LFG 🚀
   + ## Let's Get Started 🚀
   ```

   **Code snippet:**
   https://github.com/open-sauced/intro/blob/59b55ca73787bbadda275d8b4caabd5e7be0595b/01-intro.md?plain=1#L53

### Steps to reproduce

1. Open the [`01-intro.md`](https://github.com/open-sauced/intro/blob/59b55ca73787bbadda275d8b4caabd5e7be0595b/01-intro.md).
2. See the intro sentence and the title of the last section.

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by MohitKambli**
## Description

Hello.
This pull request fixes the bugs present in the **01-intro.md** file.
As mentioned in #118, I have updated the following documentation changes:
`Welcome to the "Intro to Open Source with OpenSauced" course!`
`## Let's Get Started 🚀`
Hope these changes meet the necessary requirements.
If at all there are any changes to be made, then kindly let me know.

Thanks and Regards,
Mohit Kambli

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [X] 🐛 Bug Fix
- [X] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
Fixes #118.

## Mobile & Desktop Screenshots/Recordings
None.

## Steps to QA
No testing required.

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed
- [X]  01-intro.md

## [optional] Are there any post-deployment tasks we need to perform?
No

## [optional] What gif best describes this PR or how it makes you feel?
Happy.

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Looks good to me! :) What do you think @adiati98?

**Review by adiati98 — CHANGES_REQUESTED** [review]
Hey @MohitKambli,
Thank you for taking on this! 🙌

However, can you please:

- assign yourself to the issue as mentioned in our [contributing guidelines](https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues). 
- mention the issue number in the "Related Tickets & Documents" section on the PR form with this format: Fixes #000.

For your future reference, please read the contributing guidelines in any open source project before contributing.

Please let me know once you've done. Thank you!😊

**Comment by MohitKambli** [comment]
Hello @adiati98
I am extremely sorry for not assigning this issue to myself first and then working on it.
I will make sure not to make such mistake again in future.
I have made the changes that you had mentioned in the previous comment.
Does that look fine to you or is there anything else that I need to update?

Thanks and Regards,
Mohit Kambli

**Review by adiati98 — APPROVED** [review]
Well done, @MohitKambli! 🙌
Thank you for the prompt changes!

If you haven't, you can join our community [Discord](https://discord.com/invite/U2peSNf23P). 😊

Also, check out our [pizza-verse](https://github.com/open-sauced/pizza-verse) repo if you want to contribute further! 🍕 

git merge GIF

**Pull request merged**
