### PR TITLE
feat: Add image of profile generated on README

### PR DESCRIPTION
**Pull request by Jenna59**
## Description

This PR adds a profile generated image to step 8 in: 05-how-to-contribute-to-open-source?id=getting-started and updates the text for step 8 to include a reference to the screenshot.

## What type of PR is this? (check all applicable)

- [X ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Closes https://github.com/open-sauced/intro/issues/147

## Mobile & Desktop Screenshots/Recordings

proposed-changes

## Steps to QA

1. Go to the page
2. Ensure that you can see the image from the above screenshot
3. Validate you see the thing working

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [ ] Tier 4

### CODE REVIEW

**Comment by adiati98** [comment]
Hi @Jenna59 ,
Thank you for your PR! 🙌

Can you please change `Feature` in the "Related Tickets and Documents" section to `Closes`?

Thank you. 🙂

**Comment by Jenna59** [comment]
> Hi @Jenna59 , Thank you for your PR! 🙌
> 
> Can you please change `Feature` in the "Related Tickets and Documents" section to `Closes`?
> 
> Thank you. 🙂

Done! I was also wondering if you use anything specific for linting markdown across the docs? I have the VS Code markdownlint plugin, so thought I would ask re: code formatting.

**Comment by adiati98** [comment]
> Done! I was also wondering if you use anything specific for linting markdown across the docs? I have the VS Code markdownlint plugin, so thought I would ask re: code formatting.

Any VS Code Markdown extension is okay to be used for formatting purposes. 

We do have a Markdown convention that you can check out at "[Markdown Basics](https://intro.opensauced.pizza/#/CONTRIBUTING?id=markdown-basics)" section in our Intro to Open Source course whenever you contribute to our docs. 😊

**Comment by adiati98** [comment]
Thank you for the PR and the PR form update, @Jenna59! 😄

If you haven't, you can join our community [Discord](https://discord.com/invite/U2peSNf23P). 😊

Also, check out our [pizza-verse](https://github.com/open-sauced/pizza-verse) repo if you want to contribute further! 🍕 

git merge GIF

**Review by adiati98 — APPROVED** [review]

**Comment by Haimantika** [comment]
@Jenna59 I think it will be nice if you check the `Documentation update` part under `What kind of PR this is?` 
What do you think about this @adiati98?

**Review by BekahHW — APPROVED** [review]

**Comment by adiati98** [comment]
@Haimantika absolutely. 😊 
I'd go ahead and check it 👍

**Pull request merged**
