### PR TITLE
[fix] added tips

### LINKED ISSUE #4: Feature: Section on how to add open source experiences to your resume
### Type of feature

📝 Documentation

### Current behavior

Not quite. It’s more of a suggestion 

### Suggested solution

Since this is an introductory guide on open source, I think it’d be a good idea to add an explainer guide for job searchers, especially those who are transitioning into non-tech career paths, on how to implement their open source experience in their resume. What do you think @BekahHW? 

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by CBID2**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [X] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR adds more detail on how to create an Open Source on OpenSauced. 

## Related Tickets & Documents
 Fixes #4 

## Mobile & Desktop Screenshots/Recordings

More tips on creating an Open Source Resume

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [X] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by BekahHW** [comment]
Hey @CBID2. Thanks for getting this up so fast! Looking through the file, I wonder if it makes more sense to reorganize a little bit so we can add more.

My thoughts are: 

## Develop Your Open Source Resume
Building a strong open source resume can help you showcase your skills, experience, and contributions to potential employers, collaborators, and the wider developer community.

### Effectively Highlight Your Contributions
This would include the new material you created, but also include information on providing project details (tools, libraries, size and complexity), describing your contributions (type [bug fix, feature, performance, documentation, etc.]), details on collaboration.

Let me know if you're up for implementing this or want to talk through this some more. And thanks again for this idea!

**Comment by CBID2** [comment]
> Hey @CBID2. Thanks for getting this up so fast! Looking through the file, I wonder if it makes more sense to reorganize a little bit so we can add more.
> 
> 
> 
> My thoughts are: 
> 
> 
> 
> ## Develop Your Open Source Resume
> 
> Building a strong open source resume can help you showcase your skills, experience, and contributions to potential employers, collaborators, and the wider developer community.
> 
> 
> 
> ### Effectively Highlight Your Contributions
> 
> This would include the new material you created, but also include information on providing project details (tools, libraries, size and complexity), describing your contributions (type [bug fix, feature, performance, documentation, etc.]), details on collaboration.
> 
> 
> 
> Let me know if you're up for implementing this or want to talk through this some more. And thanks again for this idea!

Hi @BekahHW! :) I like this description. It'll help users understand the importance of describing their experiences. I think adding it within my paragraph about adding metrics when highlighting open source contributions will be helpful too.

**Comment by BekahHW** [comment]
@CBID2 do you want to add that update as part of your PR?

**Comment by CBID2** [comment]
> @CBID2 do you want to add that update as part of your PR?

Sure @BekahHW!

**Comment by CBID2** [comment]
> @CBID2 do you want to add that update as part of your PR?

Did it @BekahHW! :)

**Comment by BekahHW** [comment]
Thank you, @CBID2

**Comment by CBID2** [comment]
>  [ 68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f63466b69464d44673369466f492f67697068792e676966 ](https://camo.githubusercontent.com/f80a530b31f9ee6a723cd983a30f7ff8f3a08eb06133d64654b4992b991d9c05/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f63466b69464d44673369466f492f67697068792e676966) [ ](https://camo.githubusercontent.com/f80a530b31f9ee6a723cd983a30f7ff8f3a08eb06133d64654b4992b991d9c05/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f63466b69464d44673369466f492f67697068792e676966)

I love that meme @BekahHW! :) Please DM it to me on Twitter

**Pull request merged**
