### PR TITLE
Feat: Translation - Japanese (日本語)

### PR DESCRIPTION
**Pull request by Yagasaki7K**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [x] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by Yagasaki7K** [comment]
The old pull request - which is in the commits for the same fork referring to Brazilian Portuguese - was removed in the last commit to avoid conflict with the pull request that has already been closed.

**Comment by CBID2** [comment]
Hi @Yagasaki7K. Thank you for your contribution. Our translation guidelines are still a work in progress, so please this PR will be closed for now

**Comment by Yagasaki7K** [comment]
I look forward to it being reopened and Japanese being introduced to reach even more new developers.

**Comment by CBID2** [comment]
> I look forward to it being reopened and Japanese being introduced to reach even more new developers.

How about you get you get yourself acquainted with other contributors at OpenSauced? You can find their Discord link here:

**Comment by Yagasaki7K** [comment]
> Hi @Yagasaki7K. Thank you for your contribution. Our translation guidelines are still a work in progress, so please refrain from making translations until they are in place. Also, avoid making spammy PRs. They make it difficult for maintainers to review them.

I had no intention of doing "SPAM" since they are two translations that I have a certain reach and I made myself available to do, if you understood it that way, I'm sorry. However, it was only these two languages that I was interested in helping with and I saw that I didn't have adequate support.

**Pull request closed without merging**
