### PR TITLE
Issue 149 resolved. 

### PR DESCRIPTION
**Pull request by gs-300**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [ ] Tier 4

### CODE REVIEW

**Comment by adiati98** [comment]
Hi @gs-300 ,
Thank you for your PR! 🙌

However, I'm closing this PR because there is no issue linked here.

Please read our Contributing Guide, especially [this section](https://docs.opensauced.pizza/contributing/introduction-to-contributing/#pull-requests-pr). We may close PRs with no linked issue.

That being said, please complete your PR form so we can understand and review the changes you made.

- Make sure you fill all the areas in the form.
- Provide a description of the changes that you made.
- Link the issue to the PR.

We're only reviewing this PR once we get all the information needed.
Please let us know once you've completed the form, and I'll reopen your PR.

Thank you. 🙂

**Comment by gs-300** [comment]
@adiati98 thank you for the feedback.  I apologize, I was so eager to contribute I overlooked some steps in the process.  I will make the changes and resubmit. thanks for your patience and helpful feedback!

**Comment by gs-300** [comment]
Hi @adiati98, I submitted a new pull request because I didn't know how to edit a closed request. (I figured it out after the fact) how can this be resolved?

**Comment by adiati98** [comment]
> Hi @adiati98, I submitted a new pull request because I didn't know how to edit a closed request. (I figured it out after the fact) how can this be resolved?

It's okay, @gs-300.
This PR is closed, and we'll leave it be.
We're using your new PR.

**Comment by gs-300** [comment]
> > Hi @adiati98, I submitted a new pull request because I didn't know how to edit a closed request. (I figured it out after the fact) how can this be resolved?
> 
> It's okay, @gs-300.
> This PR is closed, and we'll leave it be.
> We're using your new PR. 

Ok @adiati98, no problem

**Pull request closed without merging**
