### PR TITLE
docs: replace open-source term

### LINKED ISSUE #109: Bug: Create consistency with "open source" term
### Describe the bug

Currently, we have "open-source" and "open source" term in the course and we want to have consistency throughout the repo.

### Suggested solution

Except for file names, let's use "open source" (without hypen) term throughout the course.

### Steps to reproduce

1. Open the repo.
2. Search for "open-source" in each chapter file.
3. You will find this term in most of the chapters.

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by flushthemoney**
Replaced the "open-source" terms with "open source" without hyphen

## Description

Fixes #109 

## What type of PR is this? (check all applicable)

- [X] 🐛 Bug Fix
- [X] 📝 Documentation Update

### CODE REVIEW

**Review by BekahHW — APPROVED** [review]

**Review by adiati98 — CHANGES_REQUESTED** [review]
Hey @flushthemoney,
Thank you so much for your PR! 🙌

However, can you check the `08-additional-resources.md` file?
There are a couple of terms that you haven't updated there.

Please let me know once you've fixed them. Thanks!🙂

**Comment by adiati98** [comment]
Hey @flushthemoney, just checking in.

How's the progress of the changes?

In the meantime, I convert this PR to draft. Feel free to convert it back once you made the changes. Thank you 😊

**Comment by flushthemoney** [comment]
Hey @adiati98!

Sorry for the late response, I'll look into the file you've mentioned and make any changes required to close the PR

**Review by adiati98 — APPROVED** [review]
Well done, @flushthemoney! 🙌
Thank you for the changes! 😄

If you haven't, you can join our community [Discord](https://discord.com/invite/U2peSNf23P). 😊

git merge GIF

**Pull request merged**
