### PR TITLE
fix: Update intro.md

### LINKED ISSUE #192: Bug: Typographical error in English version
### Describe the bug

I found a typo, as discussed at https://github.com/open-sauced/intro/discussions/179

In the intro.md (English version), there's an unexpected '>' at the end of the line `starting> this course`

https://github.com/open-sauced/intro/blob/6e5f0615fb73565569dfc18339ab633f215c014f/docs/intro-to-oss/intro.md?plain=1#L9

### Steps to reproduce

Check into intro.md (line 9)
https://github.com/open-sauced/intro/blob/6e5f0615fb73565569dfc18339ab633f215c014f/docs/intro-to-oss/intro.md?plain=1#L9

### PR DESCRIPTION
**Pull request by georgepence**
Eliminate extraneous '>'  from 2nd paragraph of "Prerequisites". (replace "starting> this course" with "starting this course").

## Description

This PR removes an extraneous '>', an apparent typo, from the 2nd paragraph of "Prerequisites"

## Related Tickets & Documents

Fixes #192 

## Mobile & Desktop Screenshots/Recordings
_**Original (branch main):**_

p2

_**PR will fix to display:**_

p1

## Steps to QA

QA process:
- Navigate to [https://github.com/georgepence/intro/blob/patch-1/docs/intro-to-oss/intro.md](https://github.com/georgepence/intro/blob/patch-1/docs/intro-to-oss/intro.md)
  - Note that the third paragraph ends with: "... learn the basics before starting this course."
  - Note that the [original version](https://github.com/open-sauced/intro/blob/main/docs/intro-to-oss/intro.md) paragraph three ends with "... learn the basics before starting**>** this course." (bold mine)

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

**Review by adiati98 — CHANGES_REQUESTED** [review]
Hey @georgepence,

Thank you for your contribution! ✨ 

However, please read our [contributing guidelines](https://github.com/open-sauced/intro/blob/main/docs/CONTRIBUTING.md).

- You need to work on existing issue or open a new issue that we've triaged before you work on your changes. That said, _**please create an issue and link it to your PR template**_.
- Please _**[complete the PR template](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=fill-in-a-pull-request-template)**_. It's very important for us to be able to review your changes.

I will put this PR on draft for now. Please let me know once you've addressed above suggestions, I'll change this PR back for ready to review.

Thank you! 🙂

**Comment by adiati98** [comment]
Hey @georgepence,

You now have an issue to accompany this PR (#192).

Please comment on the issue with `.take` to assign yourself to the issue and address my previous review before I can mark this as ready for review. 🙂 

FYI, if the issue is not assigned, it's considered open for anyone to work on.

**Comment by adiati98** [comment]
@georgepence I see that you've assigned yourself to the issue. 👏🏼 

Now, you still need to complete the PR template. You can read [this section](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=fill-in-a-pull-request-template) in our course to do so.

I make this PR to ready for review so you can address each failed check in the bot messages.

**Comment by georgepence** [comment]
Please review changes.

**Comment by adiati98** [comment]
@georgepence you still have a check that needs to be addressed [here](https://github.com/open-sauced/intro/pull/188#pullrequestreview-2058902006).

**Review by adiati98 — APPROVED** [review]
Well done and thank you for your contribution, @georgepence! ✨ 

If you haven't, you can join our community [Discord](https://discord.com/invite/U2peSNf23P).
Also, check out our [pizza-verse](https://github.com/open-sauced/pizza-verse) repo if you want to contribute further! 🍕🍴

git merge GIF

**Review by BekahHW — APPROVED** [review]

**Pull request merged**
