### PR TITLE
Feat navbar

### PR DESCRIPTION
**Pull request by geoffreylgv**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Mobile & Desktop Screenshots/Recordings
image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [x] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by CBID2** [comment]
Umm... I think you cherry-picked the wrong commit @geoffreylgv.

**Comment by CBID2** [comment]
Ooh. Not quite. You were supposed to cherry-pick [this one](https://github.com/open-sauced/intro/commit/925e380a958bebf0c2ca9962f0e07938961a16dd) @geoffreylgv

**Comment by geoffreylgv** [comment]
> Ooh. Not quite. You were supposed to cherry-pick [this one](https://github.com/open-sauced/intro/commit/925e380a958bebf0c2ca9962f0e07938961a16dd) @geoffreylgv. I suggest closing this PR and try again

Ok, to pick only this [commit](https://github.com/open-sauced/intro/commit/925e380a958bebf0c2ca9962f0e07938961a16dd), right?

**Comment by CBID2** [comment]
> > Ooh. Not quite. You were supposed to cherry-pick [this one](https://github.com/open-sauced/intro/commit/925e380a958bebf0c2ca9962f0e07938961a16dd) @geoffreylgv. I suggest closing this PR and try again
> 
> 
> 
> Ok, to pick only this [commit](https://github.com/open-sauced/intro/commit/925e380a958bebf0c2ca9962f0e07938961a16dd), right?

Right @geoffreylgv

**Pull request closed without merging**
