### PR TITLE
feat: Add a step to create new branch in the CONTRIBUTING file

### LINKED ISSUE #149: Feature: Add a step to create new branch in the CONTRIBUTING file
### Type of feature

📝 Documentation

### Current behavior

We've noticed that some contributors made their changes directly on the `main` branch.

### Suggested solution

We want to make clear that changes are made on new branch and not directly on the `main` branch. 

- [ ] Add step 4 in the "[Setup the Project Locally](https://github.com/open-sauced/intro/blob/main/CONTRIBUTING.md#setup-the-project-locally)" section in the CONTRIBUTING file with copy as follow:

   ````markdown
   4. Create a new branch to work on your changes.

      ```bash
      git checkout -b YOUR-BRANCH-NAME
      ```

      Replace "YOUR-BRANCH-NAME" with a descriptive name for your branch — for example, `feat/add-submit-button`.
   ````

- [ ] Change number 4 to 5.

The code is located here:

https://github.com/open-sauced/intro/blob/c3c863688ef04649a2190332db97250867f03137/CONTRIBUTING.md?plain=1#L33-L39

---

> [!IMPORTANT]
> If you've worked on a good first issue or beginners only issue in any of our [community repositories](https://docs.opensauced.pizza/contributing/opensauced-maintainers-guide/community-maintainers-guide/#opensauced-community-repositories) before, please refrain from taking this issue.
> We may remove you from the assignees and not accept your pull request if you choose to proceed.

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by gs-300**
## Description

This Pull Request adds an additional step to the CONTRIBUTING.md file.  Which explains to contributors that a new branch should be created before making changes to local repository clone. 

Step 4. was updated and its contents moved to step 5. which was added.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Closes #149 

### Current:

Screenshot 2024-03-30 123859

### Commit (fix):

Screenshot 2024-03-30 085303

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [ ] Tier 4

## [optional] Are there any post-deployment tasks we need to perform?

no

## [optional] What gif best describes this PR or how it makes you feel?

happy face

### CODE REVIEW

**Comment by CBID2** [comment]
Hi @gs-300. When you’re filling out your Pull Request, it’s always best to place the information in the section that it corresponds to. For example, instead of putting `#149` in the `Description` section, place it in `Related Ticket and Documents` following this format:

```
Keyword #issuenumber
```
👇
```
Closes #200
```

**Comment by gs-300** [comment]
HI @CBID2, I understand and appreciate the feedback.  I just made the necessary changes to my Pull Request.  Thank you for taking the time to explain.

**Comment by adiati98** [comment]
Well done, @gs-300 ! 🙌
Thank you for the changes! 😄

If you haven't, you can join our community [Discord](https://discord.com/invite/U2peSNf23P). 😊

Also, check out our [pizza-verse](https://github.com/open-sauced/pizza-verse) repo if you want to contribute further! 🍕 

git merge GIF

**Review by adiati98 — APPROVED** [review]

**Comment by gs-300** [comment]
> Well done, @gs-300 ! 🙌
> 
> Thank you for the changes! 😄
> 
> 
> 
> If you haven't, you can join our community [Discord](https://discord.com/invite/U2peSNf23P). 😊
> 
> 
> Also, check out our [pizza-verse](https://github.com/open-sauced/pizza-verse) repo if you want to contribute further! 🍕 
> 
> 
> 
> git merge GIF

Absolutely!!! @adiati98, looking forward to it.

**Review by BekahHW — APPROVED** [review]

**Pull request merged**
