### PR TITLE
Delete redundant text content

### PR DESCRIPTION
**Pull request by Pondy007**
## Description

This PR fixes the bug https://github.com/open-sauced/intro/issues/122 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes https://github.com/open-sauced/intro/issues/122
 

## Mobile & Desktop Screenshots/Recordings
image

## Steps to QA
Please provide some steps for the reviewer to test your change. If you have wrote tests, you can mention that here instead.

1. [Click a link](https://github.com/open-sauced/intro/blob/main/translations/fr/02-qu-est-ce-que-l-open-source.md)
2. See there is no replicated text at the end

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?
Proud of my first contribution. Hope I did not forget something.
image

### CODE REVIEW

**Comment by CBID2** [comment]
Hi @Pondy007. I closed your Pull Request because it was not assigned to you yet. Please reread our contribution guidelines before submitting a pull request.

**Comment by Pondy007** [comment]
Hi @CBID2 ,
Thanks for the assignment ! You are right, one should be assigned before working on it. (My english is not as good as my french...)
Noted for next time ;-)

**Comment by Pondy007** [comment]
Hi @CBID2 ,
What should I do now concerning this PR ?
As I am the author, I cannot approve change (which is normal).
Thank you.

**Review by CBID2 — APPROVED** [review]
Sorry for the wait @Pondy007. It looks good on my end. What do you think @adiati98?

**Review by adiati98 — APPROVED** [review]
Well spot on!
Thank you, @Pondy007! 🚀

**Review by adiati98 — CHANGES_REQUESTED** [review]
@Pondy007 I just realized that you made this PR right on the `main` branch.
And we don't want to merge a PR that is worked on the `main` branch.

That said, I'm closing this PR.

The changes is already great.
You only need to create a new branch, make your changes there, then create a new PR.

Please let me know if you have any question.

Thank you!

**Comment by Pondy007** [comment]
Hi @adiati98 ,
You are absolutely right ! I realized afterwards that I did my changes on main branch. (Beginner's mistake...)
I will do what you suggested.
Thx.

**Pull request closed without merging**
