### PR TITLE
feat: create Portuguese folder

### LINKED ISSUE #16: Feature: Translate the course to other language
### Type of feature

📝 Documentation

### Current behavior

Hi, it is a perfect course for beginners and I would like to introduce it to my newborn open-source community in Angola(github.com/angolaosc), but the biggest part of my community do not speak or understand English. 

### Suggested solution

It would be perfect if we can have a translation of this course.

I will be available to contribute translating most of the part of this course into Portuguese and encourage people from my community to contribute too.

### Additional context

idiom

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by CBID2**
## Description
This PR adds a folder where the course files will be translated into Portuguese.

## What type of PR is this? (check all applicable)

- [X] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
Fixes #16 

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [X] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by antonio-pedro99** [comment]
Hi @CBID2, thanks for this PR.
But I do not think this is the way to go. 
Creating a pt-br folder under the root dir won't make the course to be scalable. It is not like we are just translating to pt-br, we should be able to start this translation in a way that translation to other language should be easy.
Right now, if we just create a folder for each translation in the root dir, we would have lot of folders there.

**Comment by CBID2** [comment]
> Hi @CBID2, thanks for this PR.
> 
> But I do not think this is the way to go. 
> 
> Creating a pt-br folder under the root dir won't make the course to be scalable. It is not like we are just translating to pt-br, we should be able to start this translation in a way that translation to other language should be easy.
> 
> Right now, if we just create a folder for each translation in the root dir, we would have lot of folders there. 

I see @Antonio

**Comment by antonio-pedro99** [comment]
I did something like this
image


> > Hi @CBID2, thanks for this PR.
> > But I do not think this is the way to go.
> > Creating a pt-br folder under the root dir won't make the course to be scalable. It is not like we are just translating to pt-br, we should be able to start this translation in a way that translation to other language should be easy.
> > Right now, if we just create a folder for each translation in the root dir, we would have lot of folders there.
> 
> I see @antonio-pedro99. What do you suggest I change?

**Comment by antonio-pedro99** [comment]
We also need to clear few things 
1. First, how we are going to show the readers that the course is available in other idioms, for now I am doing like this:

```
Welcome to the Intro to Open Source Course with OpenSauced! This course is designed to provide you with an introduction to open source and guide you through the process of contributing to open source projects. 

## Language Support

- [Portuguese](./translations/pt-br/README.pt.md)
```
2. AFAIK, we can only provide one sidebar in the index.html, which will be persistent to all other subpages. 
How can we tackle this?

**Comment by CBID2** [comment]
> I did something like this image
> 
> > > Hi @CBID2, thanks for this PR.
> > > But I do not think this is the way to go.
> > > Creating a pt-br folder under the root dir won't make the course to be scalable. It is not like we are just translating to pt-br, we should be able to start this translation in a way that translation to other language should be easy.
> > > Right now, if we just create a folder for each translation in the root dir, we would have lot of folders there.
> > 
> > 
> > I see @antonio-pedro99. What do you suggest I change?

 @antonio-pedro99, I changed the folder structure. As far as navigation, definitely add to the English version of the ReadMe.

**Comment by CBID2** [comment]
> We also need to clear few things
> 
> 1. First, how we are going to show the readers that the course is available in other idioms, for now I am doing like this:
> 
> ```
> Welcome to the Intro to Open Source Course with OpenSauced! This course is designed to provide you with an introduction to open source and guide you through the process of contributing to open source projects. 
> 
> ## Language Support
> 
> - [Portuguese](./translations/pt-br/README.pt.md)
> ```
> 
> 2. AFAIK, we can only provide one sidebar in the index.html, which will be persistent to all other subpages.
>    How can we tackle this?

Since we're only focusing on one language, this information to the Readme would be the best option for now @antonio-pedro99.

**Comment by antonio-pedro99** [comment]
@CBID2 good. 
I have created these files in my fork xD.
I don't have write permission to your fork, so I can not add changes directly to this branch. Instead, I have forked the repo from your branch and made the required changes. 
I was in a process of creating a new PR with your initial changes.

**Comment by CBID2** [comment]
> @CBID2 good. 
> 
> I have created these files in my fork xD.
> 
> I don't have write permission to your fork, so I can not add changes directly to this branch. Instead, I have forked the repo from your branch and made the required changes. 
> 
> I was in a process of creating a new PR with your initial changes. 

Oh sorry @antonio-pedro99 lol

**Pull request closed without merging**
