### PR TITLE
[#122] docs:Delete duplicated text

### LINKED ISSUE #122: Bug: Text repeated twice on french translation
### Describe the bug

Hi everyone (this is my first time reporting an issue on github) !
On the french translation, chapter 2, the text is repeated twice. From line 71 to 139.
One should remove it.

### Steps to reproduce

1. Go to https://github.com/open-sauced/intro/blob/main/translations/fr/02-qu-est-ce-que-l-open-source.md
2. See that same text is repeated beginning from line 71 to 139

### Browsers

Chrome

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by Pondy007**
## Description

This PR fixes bug #122 : 
- file : translations/fr/02-qu-est-ce-que-l-open-source.md 
- Delete whole duplicated text (from line 70 to 139)

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
Fix #122

## Mobile & Desktop Screenshots/Recordings
NA

## Steps to QA
1. Go to french translation, chapter 2 : "Qu'est-ce que l'open-source ?"
2. Verify there is no replicated text at the end

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?
Happy-emoji-2

### CODE REVIEW

**Review by adiati98 — APPROVED** [review]
@Pondy007 
It looks good to me! 🚀

thank you gif

**Review by CBID2 — APPROVED** [review]
You did great @Pondy007! :)

**Comment by Pondy007** [comment]
Thank you @adiati98 & @CBID2 !
Have a great day !

**Comment by CBID2** [comment]
> Thank you @adiati98 & @CBID2 !
> 
> Have a great day !

You too mon ami! 😊

**Pull request merged**
