### PR TITLE
feat:add scroll-to-top

### PR DESCRIPTION
**Pull request by vrun1208**
## Description
Added a `ScrollToTop` button in order to ensure better user experience!

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by CBID2** [comment]
Thanks for contributing @vrun1208, but I'm not sure how it fits with the project. Can you explain?

**Comment by vrun1208** [comment]
> Thanks for contributing @vrun1208, but I'm not sure how it fits with the project. Can you explain?

Hi @CBID2, actually for desktop view it does not much needed but in mobile view there are long readings and unnecessary scrolling from bottom to top on same page while reading docs.

**Comment by CBID2** [comment]
> > Thanks for contributing @vrun1208, but I'm not sure how it fits with the project. Can you explain?
> 
> 
> 
> Hi @CBID2, actually for desktop view it does not much needed but in mobile view there are long readings and unnecessary scrolling from bottom to top on same page while reading docs.  

I'm still unsure @vrun1208.

**Comment by CBID2** [comment]
@open-sauced/community, what do you think about this contribution?

**Comment by CBID2** [comment]
Hi @vrun1208. After a discussion with the team, we decided to not accept this contribution. While this feature is nice to have, the course is not too long to scroll at the moment, even on mobile. Additionally, our hamburger menu on the bottom also makes easier to navigate between sections on mobile. In future, please raise an issue, wait until it gets approved before making a pull request(link the issue to your PR form too).

**Comment by vrun1208** [comment]
> Hi @vrun1208. After a having discussion with the team, we decided to not accept this contribution. While this feature is nice to have, the course is not too long to scroll at the moment, even on mobile. Additionally, our hamburger menu on the bottom also makes easier to navigate between sections on mobile. In future, please raise an issue, wait until it gets approved and assigned to you before making a pull request(link the issue to your PR form too).

Yeah, That's okay!, I'll surely come up with a new issue soon🚀

**Pull request closed without merging**
