### PR TITLE
feat: Adding a sentence

### LINKED ISSUE #175: Feature: Add a link to the "Job Seekers Guide"
### Current behavior

> [!IMPORTANT]
> If you've worked on a "beginner only" issue or "good first issue" in any of our [community repositories](https://docs.opensauced.pizza/contributing/opensauced-maintainers-guide/community-maintainers-guide/#opensauced-community-repositories) before, please refrain from taking this issue.
> We may remove you from the assignees and not accept your pull request if you choose to proceed.

We have a "Job Seekers Guide" in our docs that is suitable to be added into the "Intro to Open Source" course.

### Suggested solution

In line 75 in the [`docs/intro-to-oss/the-secret-sauce.md`](https://github.com/open-sauced/intro/blob/main/docs/intro-to-oss/the-secret-sauce.md), add a sentence at the end with copy as follow:

```markdown
Additionally, you can refer to the [Job Seekers Guide](https://docs.opensauced.pizza/opensauced-guides/job-seekers-guide/job-seekers-guide-introduction/) on our docs to learn how to use OpenSauced to land a job in the tech industry.
```

Code to be improved:

https://github.com/open-sauced/intro/blob/5476877fcc352429459a28c6a2f72083a78ff095/docs/intro-to-oss/the-secret-sauce.md?plain=1#L75

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by NeilGeorge1**
Added the required sentence

## Description
This PR adds the required sentence after the full stop at line 75 in the code.

## Related Tickets & Documents
Closes #175 

## Mobile & Desktop Screenshots/Recordings
Screenshot 2024-05-17 210525

## Steps to QA
1. Open the file [the-secret-sauce.md](https://github.com/open-sauced/intro/blob/main/docs/intro-to-oss/the-secret-sauce.md) on GitHub.
2. Navigate to line 75.
3. Check if the required sentence has been added after the full stop at line 75.
4. If there are any issues or changes required, please provide details in the comments section of the PR.

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

**Review by adiati98 — CHANGES_REQUESTED** [review]
Thank you for your contribution, @NeilGeorge1! ✨

However, there are some [checks that failed](https://github.com/open-sauced/intro/pull/194#pullrequestreview-2058486687).
Please address each of them until all checks pass befire we can review your PR.

Let us know if you have questions or need help.

Thank you. 🙂

**Comment by NeilGeorge1** [comment]
No problem! @adiati98 
Sure i'll address them rightaway

**Comment by adiati98** [comment]
Hi @NeilGeorge1,

You still have one [failed check here](https://github.com/open-sauced/intro/pull/194#pullrequestreview-2058486687).
Please read the message carefully so you can resolve the bot. 🙂

**Review by BekahHW — COMMENTED** [review]
nit pick: on our docs to learn how to use OpenSauced to land a job in the tech industry.

Instead of "on our docs" let's use "in our docs"

**Comment by NeilGeorge1** [comment]
Hello @adiati98 
Sorry this was my first time I will try resolving this.
@BekahHW Sure will do the necessary changes

**Review by adiati98 — APPROVED** [review]

**Review by BekahHW — APPROVED** [review]

**Pull request merged**
