### PR TITLE
Issue 6 docsify site

### PR DESCRIPTION
**Pull request by FahimFBA**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [x] 🎨 Style
- [x] 🤖 Build
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

Created a `docsify` static website.

## Related Tickets & Documents

#6 

## Mobile & Desktop Screenshots/Recordings

image

image
image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?
I am confused about whether you want me to add the content to the navbar.
Also I need to know about the favicon choice if have any.

### CODE REVIEW

**Comment by BekahHW** [comment]
It would be great if you could add it to the navbar! If you can use the logo as the favicon, that would great. Here's a link to our assets: https://opensauced.pizza/press. Let me know if you need anything else.

This is looking great!

**Comment by FahimFBA** [comment]
> It would be great if you could add it to the navbar! If you can use the logo as the favicon, that would great. Here's a link to our assets: https://opensauced.pizza/press. Let me know if you need anything else.
> 
> This is looking great!

Sure! Give me a few days.

**Comment by FahimFBA** [comment]
Everything is done. Let me know how it looks. The color can be changed in the GitHub icon easily.

For running it locally:

1. Install **docsify** globally: `npm i docsify-cli -g`
2. Launch using `docsify serve`

Screenshot (13)
Screenshot (14)
Screenshot (15)
Screenshot (16)
Screenshot (17)
Screenshot (18)

**Review by bdougie — APPROVED** [review]
You can check it out locally, and it works for me. With this leveraging the index.html it seems to be a simple deploy.

Since our domain is managed on netlify, I will point the repo to there to make sure https://intro.opensauced.pizza works.

**Comment by FahimFBA** [comment]
> You can check it out locally, and it works for me. With this leveraging the index.html it seems to be a simple deploy.
> 
> Since our domain is managed on netlify, I will point the repo to there to make sure https://intro.opensauced.pizza works.

If I would know about the domain, then I could make the navbar pointing to the specific domain's page. Please let me know if you would need me to work on that too.

**Comment by FahimFBA** [comment]
> @FahimFBA https://intro.opensauced.pizza/ is now live.

Wow! Looks good. Thank you so much.

**Comment by BekahHW** [comment]
Thanks so much @FahimFBA!!!

**Pull request merged**
