### PR TITLE
feat: add test button (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by CBID2**
## Description
This is just a test to see if [Michael's cheatsheet for the edit button works](https://michaelcurrin.github.io/dev-cheatsheets/cheatsheets/jekyll/templating/edit-this-page.html)

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [X] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Relates to #75 
## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [X] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [X] 🙅 no documentation needed

### CODE REVIEW

**Comment by adiati98** [comment]
Hey @CBID2,

I've checked this out :)

- We want to make it the same/similar as the `docs` as below:

  edit page

  while now we're having this:

  edit on GitHub

  I'm not sure which icon we use at `docs`, but maybe we can make the text the same as `docs`, and put the icon on the left side?

- When I click the link to edit on GitHub, it goes to the same page — ([Edit this page on GitHub 📝](https://intro.opensauced.pizza/#/)). Is this intentional for testing purpose?

  When I click "Edit this page" on `docs`, it will open the [edit page](https://github.com/open-sauced/docs/edit/main/docs/introduction.md) on GitHub. So we might want to link it this way.
  
  I also noticed, `docs` repo has a "docs" folder, which is in line with the [docsify docs](https://docsify.js.org/#/quickstart?id=writing-content). I'm not quite sure if we should create a docs folder as well here.

**Comment by CBID2** [comment]
> Hey @CBID2,
> 
> 
> 
> I've checked this out :)
> 
> 
> 
> - We want to make it the same/similar as the `docs` as below:
> 
> 
> 
>   edit page
> 
> 
> 
>   while now we're having this:
> 
> 
> 
>   edit on GitHub
> 
> 
> 
>   I'm not sure which icon we use at `docs`, but maybe we can make the text the same as `docs`, and put the icon on the left side?
> 
> 
> 
> - When I click the link to edit on GitHub, it goes to the same page — ([Edit this page on GitHub 📝](https://intro.opensauced.pizza/#/)). Is this intentional for testing purpose?
> 
> 
> 
>   When I click "Edit this page" on `docs`, it will open the [edit page](https://github.com/open-sauced/docs/edit/main/docs/introduction.md) on GitHub. So we might want to link it this way.
> 
>   
> 
>   I also noticed, `docs` repo has a "docs" folder, which is in line with the [docsify docs](https://docsify.js.org/#/quickstart?id=writing-content). I'm not quite sure if we should create a docs folder and move the content in the folder as well here.
> 
> 
> 
>   
> 
> 
> 
> 

@adiati98, thanks for the feedback. Yeah I meant to link it to the actual GitHub page. To the point about using the button design that's in the docs repo, I originally planned on using the extension docsify recommended but it's outdated: https://github.com/njleonzhang/docsify-edit-on-github/blob/master/README.md#

**Comment by adiati98** [comment]
> > Hey @CBID2,
> > 
> > 
> > 
> > I've checked this out :)
> > 
> > 
> > 
> > - We want to make it the same/similar as the `docs` as below:
> > 
> > 
> > 
> >   edit page
> > 
> > 
> > 
> >   while now we're having this:
> > 
> > 
> > 
> >   edit on GitHub
> > 
> > 
> > 
> >   I'm not sure which icon we use at `docs`, but maybe we can make the text the same as `docs`, and put the icon on the left side?
> > 
> > 
> > 
> > - When I click the link to edit on GitHub, it goes to the same page — ([Edit this page on GitHub 📝](https://intro.opensauced.pizza/#/)). Is this intentional for testing purpose?
> > 
> > 
> > 
> >   When I click "Edit this page" on `docs`, it will open the [edit page](https://github.com/open-sauced/docs/edit/main/docs/introduction.md) on GitHub. So we might want to link it this way.
> > 
> >   
> > 
> >   I also noticed, `docs` repo has a "docs" folder, which is in line with the [docsify docs](https://docsify.js.org/#/quickstart?id=writing-content). I'm not quite sure if we should create a docs folder and move the content in the folder as well here.
> > 
> > 
> > 
> >   
> > 
> > 
> > 
> > 
> 
> @adiati98, thanks for the feedback. Yeah I meant to link it to the actual GitHub page. To the point about using the button design that's in the docs repo, I originally planned on using the extension docsify recommended but it's outdated: https://github.com/njleonzhang/docsify-edit-on-github/blob/master/README.md#
> 

We can try it first. If it doesn't work, then we can let it go 😊

**Comment by CBID2** [comment]
> > > Hey @CBID2,
> > > 
> > > 
> > > 
> > > I've checked this out :)
> > > 
> > > 
> > > 
> > > - We want to make it the same/similar as the `docs` as below:
> > > 
> > > 
> > > 
> > >   edit page
> > > 
> > > 
> > > 
> > >   while now we're having this:
> > > 
> > > 
> > > 
> > >   edit on GitHub
> > > 
> > > 
> > > 
> > >   I'm not sure which icon we use at `docs`, but maybe we can make the text the same as `docs`, and put the icon on the left side?
> > > 
> > > 
> > > 
> > > - When I click the link to edit on GitHub, it goes to the same page — ([Edit this page on GitHub 📝](https://intro.opensauced.pizza/#/)). Is this intentional for testing purpose?
> > > 
> > > 
> > > 
> > >   When I click "Edit this page" on `docs`, it will open the [edit page](https://github.com/open-sauced/docs/edit/main/docs/introduction.md) on GitHub. So we might want to link it this way.
> > > 
> > >   
> > > 
> > >   I also noticed, `docs` repo has a "docs" folder, which is in line with the [docsify docs](https://docsify.js.org/#/quickstart?id=writing-content). I'm not quite sure if we should create a docs folder and move the content in the folder as well here.
> > > 
> > > 
> > > 
> > >   
> > > 
> > > 
> > > 
> > > 
> > 
> > @adiati98, thanks for the feedback. Yeah I meant to link it to the actual GitHub page. To the point about using the button design that's in the docs repo, I originally planned on using the extension docsify recommended but it's outdated: https://github.com/njleonzhang/docsify-edit-on-github/blob/master/README.md#
> > 
> 
> We can try it first. If it doesn't work, then we can let it go 😊

I tried it and it did not work lol 😂

**Comment by CBID2** [comment]
> ✏️

Made the change @adiati98. Here's how it looks:
edit this page example

**Comment by adiati98** [comment]
It looks much better, @CBID2!

As for the link, let's make it similar with our [docs](https://docs.opensauced.pizza/). If you click the "Edit this page" link, it will bring user to the editing page.

So we want to navigate to the edit page [such as this one](https://github.com/open-sauced/intro/edit/main/01-intro.md) for the intro instead of the blob.

**Comment by CBID2** [comment]
> It looks much better, @CBID2!
> 
> As for the link, let's make it similar with our [docs](https://docs.opensauced.pizza/). If you click the "Edit this page" link, it will bring user to the editing page.
> 
> So we want to navigate to the edit page [such as this one](https://github.com/open-sauced/intro/edit/main/01-intro.md) for the intro instead of the blob.

Hi @adiati98. I made the change! :) @BekahHW, I think this is how we should put the edit "buttons" for now and then come back to it in the future.

**Comment by BekahHW** [comment]
@CBID2 sounds good to me. Are you going to put that on all the pages?

**Comment by CBID2** [comment]
> @CBID2 sounds good to me. Are you going to put that on all the pages?

Yes @BekahHW

**Comment by CBID2** [comment]
Hey @BekahHW. Made the changes on PR #75

**Pull request closed without merging**
